[package]
name = "gravel-demo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
gravel.path = "../gravel"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  """cfg(device_name, values(
    "aplite",
    "basalt",
    "chalk",
    "diorite",
    "emery",
    "flint",
    "gabbro",
  ))""",
  'cfg(device_shape, values("rect", "round"))',
  'cfg(device_gamut, values("bw", "color"))',
  'cfg(device_feature, values(any()))',
] }
