#!python (for filetype detection)

import os.path
from waflib.TaskGen import extension, feature, before_method

top = "."
out = "build"


def concat_args(*args: list[str]) -> str:
    return " ".join(args)


@extension(".a")
def add_artifact_file(self, node):
    self.add_those_o_files(node)


def options(ctx):
    ctx.load("pebble_sdk")


def configure(ctx):
    ctx.load("pebble_sdk")

    for platform in ctx.env.TARGET_PLATFORMS:
        platform_env = ctx.all_envs[platform]
        platform_env.LINKFLAGS += ["-z", "noexecstack"]
        platform_env.LINKFLAGS += ["-Wl,--no-warn-rwx-segments"]  # ¯\_(ツ)_/¯


def build(ctx):
    ctx.load("pebble_sdk")

    binaries = []
    base_env = ctx.env

    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        platform_name = ctx.env.PLATFORM_NAME
        build_dir = ctx.env.BUILD_DIR
        ctx.set_group(platform)

        # TODO: This code shouldn't depend on project name.
        # The name defined in package.json is pretty easy to access from this build script,
        # but the name that Rust uses comes from Cargo.toml, and there's no guarantee they match.
        rlib_name = "libgravel_demo.a"

        rlib_task = ctx(
            rule=concat_args(
                f"TARGET_DEVICE={platform_name}",
                "cargo build",
                # TODO: support dev builds with debuginfo and whatever pebble build --dev does
                "--release",
                "-Z build-std=core,alloc",
                "-Z json-target-spec",
                "--target ../thumbv7m-pebble-eabi.json",
                "--target-dir .",
                "-Z unstable-options",
                f"--artifact-dir {build_dir}",
            ),
            source=[
                "./Cargo.toml",
                "./thumbv7m-pebble-eabi.json",
                *ctx.path.ant_glob("src/**.rs"),
            ],
            stderr=None,
            target=f"{build_dir}/{rlib_name}",
        )

        elf_task = ctx.pbl_program(
            features="fake_obj",
            source=[rlib_task.target],
            target=f"{build_dir}/pebble-app.elf",
        )
        binaries.append({"platform": platform, "app_elf": elf_task.target})

    ctx.env = base_env
    ctx.set_group("bundle")
    ctx.pbl_bundle(binaries=binaries)
